# ---------- Deployment ----------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpletimeservice-deployment
  labels:
    app: simpletimeservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simpletimeservice
  template:
    metadata:
      labels:
        app: simpletimeservice
    spec:
      containers:
        - name: simpletimeservice
          image: sudalai29/simpletimeservice:latest
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

---

# ---------- Service ----------
apiVersion: v1
kind: Service
metadata:
  name: simpletimeservice
spec:
  type: NodePort
  selector:
    app: simpletimeservice
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30036
